# The 'version' tag is obsolete and can be removed.
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=abq_transit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./python_app
    container_name: python_app
    depends_on:
      - db
    environment:
      - DB_NAME=abq_transit
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db

# This top-level 'volumes' block defines the named volume.
# It should not be indented.
volumes:
  postgres_data: {}